router id /* FIXME */;

define myip	= /* FIXME */;

function is_valid_dn42() -> bool {
	return net ~ [ fd00::/8{44,64} ];
}

function is_valid_internal() -> bool {
	return net ~ [ fd00::/8{64,128} ];
}

protocol direct {
	ipv6 {
		export none;
		import filter {
			if is_valid_internal() then
				accept;
			else
				reject;
		};
	};

	interface "catmint-dummy";
};

protocol device {
	scan time 20;
};

protocol kernel {
	scan time 20;

	ipv6 {
		import none;

		export filter {
			if source ~ [ RTS_STATIC, RTS_DEVICE ] then
				reject;

			krt_prefsrc = myip;
			accept;
		};
	};
};

protocol ospf v3 internal_42 {
	ipv6 {
		import filter {
			if is_valid_internal() then
				accept;
			else
				reject;
		};

		export filter {
			if is_valid_internal() then
				accept;
			else
				reject;
		};
	};

	area 1750 {
		interface "FIXME" {
			hello 15;
			authentication cryptographic;
			password "FIXME";
		};
	};
};
